### ISSUE TITLE
[WORKSPACE; 19.2 fabric] World Crash on lighting issue

### ISSUE THREAD

**Issue by Shibva** [FallingColors/HexMod#414]
"Bandaid" applied in commit linked below

## Information:

Version used: Workspace Development
Workspace Instance: 1.19.2
Launcher Instance/Version: Farbic
Workspace Itteration used: as of Commit 588a554efa436138ba067f9f608b1a10e2ca7c63

Issue: Upon world Load after a minute or so the workspace crashes wtih an error regarding a lighting issue

Additional Info: issue ceased when Phosphorus was disabled from the workspace

## Crash Report [GameLog if former is not available]: 
[crash-2023-02-15_17.18.43-client.txt](https://github.com/gamma-delta/HexMod/files/10760107/crash-2023-02-15_17.18.43-client.txt)
Report POI: ```Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.world.level.lighting.LayerLightEngine.method_15483(long)'
	at net.minecraft.world.level.lighting.LayerLightEngine.cancelUpdatesForChunk(LayerLightEngine.java:698)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.handler$beg000$preRemoveSection(LayerLightSectionStorage.java:816)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.clearQueuedSectionBlocks(LayerLightSectionStorage.java)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.addQueuedLightmaps(LayerLightSectionStorage.java:1423)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.markNewInconsistencies(LayerLightSectionStorage.java:852)
	at net.minecraft.world.level.lighting.LayerLightEngine.runUpdates(LayerLightEngine.java:186)
	at net.minecraft.world.level.lighting.LevelLightEngine.runUpdates(LevelLightEngine.java:63)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1198)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:816)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1177)
	at net.minecraft.client.Minecraft.run(Minecraft.java:768)
	at net.minecraft.client.main.Main.run(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.lighting.LayerLightEngine.cancelUpdatesForChunk(LayerLightEngine.java:698)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.handler$beg000$preRemoveSection(LayerLightSectionStorage.java:816)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.clearQueuedSectionBlocks(LayerLightSectionStorage.java)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.addQueuedLightmaps(LayerLightSectionStorage.java:1423)
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.markNewInconsistencies(LayerLightSectionStorage.java:852)
	at net.minecraft.world.level.lighting.LayerLightEngine.runUpdates(LayerLightEngine.java:186)
	at net.minecraft.world.level.lighting.LevelLightEngine.runUpdates(LevelLightEngine.java:63)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1198)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)
```

**Comment by gamma-delta** [comment]
Have you made sure it doesn't happen without hex casting? I don't see what in hex could be causing this

**Comment by Shibva** [comment]
How would I do that? It's literally what the workspace is built off of.


But if it's any correlation, I am using the computer with an AMD radon graphics card

**Comment by Shibva** [comment]
To be honest, that would be more plausible… Considering there's some drinking shit that goes on between Nvidia and AMD

**Comment by Shibva** [comment]
Recommended course of action: make an addendum or some thing to notify the user to disable phosphorus if they're running into any issues and/or if they are using AMD graphics, as it may be just a case of phosphor being more designed to run on the Nvidia graphics than AMD graphics, which is plausible

**Comment by object-Object** [comment]
I don't really see how this is our problem?
