### ISSUE TITLE
1.20.1 unbound circles unable to cast archers distillation

### ISSUE THREAD

**Issue by Yorklag** [FallingColors/HexMod#668]
### Modloader

Fabric

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-634

### Modloader version

Fabric Loader 0.15.9 + Fabric API 0.92.1+1.20.1

### Modpack info

hexxycraft 1.20.1 pack

### Issue description

unbound cleric impetus circles are unable to perform raycasts with archers distillation
![image](https://github.com/FallingColors/HexMod/assets/74254148/521336dc-6bcb-424a-a04d-eeea2f74f05f)

**Comment by object-Object** [comment]
Minimal reproducible example:

![image](https://github.com/FallingColors/HexMod/assets/37044997/4c4d026d-78de-4296-82de-f5e7bdb63877)

Full traceback from `latest.log`:

```
java.lang.NullPointerException: null cannot be cast to non-null type net.minecraft.world.entity.Entity
	at at.petrak.hexcasting.common.casting.actions.raycast.OpBlockRaycast.execute(OpBlockRaycast.kt:31)
	at at.petrak.hexcasting.api.casting.castables.ConstMediaAction$DefaultImpls.executeWithOpCount(ConstMediaAction.kt:23)
	at at.petrak.hexcasting.common.casting.actions.raycast.OpBlockRaycast.executeWithOpCount(OpBlockRaycast.kt:16)
	at at.petrak.hexcasting.api.casting.castables.ConstMediaAction$DefaultImpls.operate(ConstMediaAction.kt:34)
	at at.petrak.hexcasting.common.casting.actions.raycast.OpBlockRaycast.operate(OpBlockRaycast.kt:16)
	at at.petrak.hexcasting.api.casting.iota.PatternIota.execute(PatternIota.java:103)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.executeInner(CastingVM.kt:114)
	at at.petrak.hexcasting.api.casting.eval.vm.FrameEvaluate.evaluate(FrameEvaluate.kt:39)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.queueExecuteAndWrapIotas(CastingVM.kt:53)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.queueExecuteAndWrapIota(CastingVM.kt:33)
	at at.petrak.hexcasting.common.blocks.circles.BlockSlate.acceptControlFlow(BlockSlate.java:96)
	at at.petrak.hexcasting.api.casting.circles.CircleExecutionState.tick(CircleExecutionState.java:237)
	at at.petrak.hexcasting.api.casting.circles.BlockEntityAbstractImpetus.tickExecution(BlockEntityAbstractImpetus.java:125)
	at at.petrak.hexcasting.api.block.circle.BlockAbstractImpetus.tick(BlockAbstractImpetus.java:64)
	at at.petrak.hexcasting.common.blocks.circles.impetuses.BlockRedstoneImpetus.tick(BlockRedstoneImpetus.java:76)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1113)
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:728)
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215)
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:323)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824)
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:105)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Tested on d89fd9134.
