### ISSUE TITLE
Patchouli great spell rendering may not be working properly

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#691]
### Modloader

Quilt

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7-pre-637

### Modloader version

Quilt Loader 0.26.0 / QSL 7.5.0+0.91.0 

### Issue description

There have been a couple mentions on Discord about patterns in the ingame book either being displayed as per-world when they shouldn't, or not being displayed as per-world when they should.

![image](https://github.com/FallingColors/HexMod/assets/37044997/7ecf510d-9e20-449b-b7c9-bd83271d9ba7)

![image](https://github.com/FallingColors/HexMod/assets/37044997/b72c3a53-aa1f-43a1-a890-4a62c643c8c6)

Note that this is apparently not an issue in the hexdoc web book: https://hexcasting.hexxy.media/v/latest/main/en_us/#patterns/stackmanip@hexcasting:rotate

### Other information

The following traceback was posted in relation to a HexDim issue:
```
[00:58:26] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@1a6bf048, suppressing error
java.lang.NullPointerException: Cannot invoke "at.petrak.hexcasting.api.casting.math.HexPattern.serializeToNBT()" because "pat" is null
at at.petrak.hexcasting.common.loot.AddPerWorldPatternToScrollFunc.doStatic(AddPerWorldPatternToScrollFunc.java:52) ~[hexcasting-0.11.1-7-pre-637.i0:0/:0.11.1-7-pre-637]
at at.petrak.hexcasting.common.loot.AddPerWorldPatternToScrollFunc.method_522(AddPerWorldPatternToScrollFunc.java:61) ~[hexcasting-0.11.1-7-pre-637.i0:0/:0.11.1-7-pre-637]
at net.minecraft.class_120.method_521(class_120.java:31) ~[minecraft-1.20.1.i0:0/:?]
at at.petrak.hexcasting.common.loot.AddPerWorldPatternToScrollFunc.apply(AddPerWorldPatternToScrollFunc.java:30) ~[hexcasting-0.11.1-7-pre-637.i0:0/:0.11.1-7-pre-637]
at net.minecraft.class_117.method_514(class_117.java:14) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_117.method_514(class_117.java:14) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_77.method_433(class_77.java:33) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_85$1.method_426(class_85.java:59) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_55.method_345(class_55.java:73) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_55.method_341(class_55.java:96) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_52.method_328(class_52.java:86) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_52.method_320(class_52.java:103) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_52.method_319(class_52.java:116) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_52.method_329(class_52.java:136) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2621.method_11289(class_2621.java:82) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2621.createMenu(class_2621.java:154) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2281.method_9534(class_2281.java:207) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[minecraft-1.20.1.i0:0/:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by object-Object** [comment]
Can't reproduce on Fabric or Quilt with just Hex Casting, so this is _probably_ a Hexxy Dimensions issue.

**Comment by object-Object** [comment]
Also can't reproduce on either platform with HexDim.

**Comment by walksanatora** [comment]
I was able to get a similar issue on forge where all my great spells were not being marked as such. but I chalked that one up to tags failing to load... it may be a similar thing (no clue how to fix it though)

**Comment by object-Object** [comment]
if you can still make it happen, please give detailed reproduction steps.

**Comment by SamsTheNerd** [comment]
I also can't reproduce this on latest build (singleplayer or multiplayer), so I'm gonna assume it was some addon issue or something. Feel free to re-open if you're able to reproduce it.
