### ISSUE TITLE
Can't join a single player world (Connection Lost)

### ISSUE THREAD

**Issue by JasdanVM** [FallingColors/HexMod#768]
### Modloader

Fabric

### Minecraft version

1.20.1

### Hex Casting version

hexcasting-fabric-1.20.1-0.11.1-7-pre-676

### Modloader version

Fabric Loader 0.16.5 / Fabric API 0.92.2+1.20.1

### Modpack info

Custom modpack, not yet published 

### The latest.log file

https://mclo.gs/t9CTcMu

### Issue description

The game starts seemingly fine, but I can't even get to load a single player world, the following screen appears:
![2024-10-05_21 34 25](https://github.com/user-attachments/assets/3438d4d8-1c31-417a-bf1a-b51b9be0c31e)

### Steps to reproduce

Load up the game, try to load a world, then fail

### Other information

I happened to install this Hexcasting Addon:
https://modrinth.com/mod/hexdim

**Comment by SamsTheNerd** [comment]
Does it load without hexdim? what about without hex at all? The log file only mentions a mod called amethyst shield, is that the full log file?

**Comment by object-Object** [comment]
Please post the actual logs/latest.log file from when you got that error. The file you posted seems to be a totally unrelated crash report, not a log file.

**Comment by JasdanVM** [comment]
> Please post the actual `logs/latest.log` file from when you got that error. The file you posted seems to be a totally unrelated crash report, not a log file.

Sorry, must be an error of the Modrinth App, because I don't have that mod anymore (Amethyst Shield)
No idea why it's showing it at all.

**Comment by JasdanVM** [comment]
[latest.log](https://github.com/user-attachments/files/17268361/latest.log)

**Comment by JasdanVM** [comment]
I'll make more tests in a a little while, as far as I know, I only added Hex Casting and that addon before the error appeared.

**Comment by vgskye** [comment]
> [latest.log](https://github.com/user-attachments/files/17268361/latest.log)

uploaded to https://mclo.gs/GZlTM1j

**Comment by vgskye** [comment]
stacktrace seems to point to a mod called exposure?

**Comment by object-Object** [comment]
yeah, I'm not seeing anything related to Hex here.

full error:

```
[21:34:10] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "exposure:sync_lenses"
java.lang.IndexOutOfBoundsException: readerIndex(15) + length(1) exceeds writerIndex(15): UnpooledSlicedByteBuf(ridx: 15, widx: 15, cap: 15/15, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 15, cap: 15))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.82.Final.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1303) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10816(class_2540.java:530) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_42064(class_2540.java:188) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10819(class_2540.java:667) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java:131) ~[client-intermediary.jar:?]
	at io.github.mortuusars.exposure.network.packet.client.SyncLensesS2CP.fromBuffer(SyncLensesS2CP.java:42) ~[exposure-1.20.1-1.7.7-fabric.jar:?]
	at io.github.mortuusars.exposure.network.fabric.ClientPackets$ClientHandler.receive(ClientPackets.java:42) ~[exposure-1.20.1-1.7.7-fabric.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.minecraft.class_634.handler$gfb000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3768) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$000(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel$1.run(LocalChannel.java:68) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

open an issue with Exposure probably.
